#! /bin/zsh

ln -s -f ~/dotfiles/zshrc ~/.zshrc
ln -s -f ~/dotfiles/vimrc ~/.vimrc
ln -s -f ~/dotfiles/tmux.conf ~/.tmux.conf

mkdir ~/.dotfiles-local

touch ~/.dotfiles-local/zshrc
touch ~/.dotfiles-local/vimrc

