#! /bin/zsh

if [[ $# < 1 || "$1" != "--force" ]]; then
    print "This command erases existing .vimrc, .tmux.conf, .zshrc files and .vim folder"
    print "Use force parameter to acknowledge you are aware:"
    print "  setup --force"
    exit 1
fi

ln -s -f ~/dotfiles/zshrc ~/.zshrc
ln -s -f ~/dotfiles/vimrc ~/.vimrc
ln -s -f ~/dotfiles/tmux.conf ~/.tmux.conf
if [ -d ~/.vim ]; then
    print "Removing existing directory ~/.vim"
    rm -r ~/.vim
fi
ln -s -f ~/dotfiles/vim ~/.vim

mkdir -p ~/.dotfiles-local

touch ~/.dotfiles-local/zshrc
touch ~/.dotfiles-local/vimrc
touch ~/.dotfiles-local/tmux.conf
