#!/bin/zsh

set -e
set -u

DIR="$( cd "$( dirname "$0" )" && pwd )"

if [[ $# < 1 || "$1" != "--force" ]]; then
    print "This command erases existing .vimrc, .tmux.conf, .zshrc files and .vim folder"
    print "Use force parameter to acknowledge you are aware:"
    print "  setup --force"
    exit 1
fi

ln -s -f ~/dotfiles/zshrc ~/.zshrc
ln -s -f ~/dotfiles/vimrc ~/.vimrc
ln -s -f ~/dotfiles/ideavimrc ~/.ideavimrc
ln -s -f ~/dotfiles/tmux.conf ~/.tmux.conf
if [ -d ~/.vim ]; then
    print "Removing existing directory ~/.vim"
    rm -r ~/.vim
fi
ln -s -f ~/dotfiles/vim ~/.vim

mkdir -p ~/dotfiles/vim/swap
mkdir -p ~/dotfiles/vim/undo
mkdir -p ~/dotfiles/vim/autoload
mkdir -p ~/dotfiles/vim/bundle

mkdir -p ~/.dotfiles-local
touch ~/.dotfiles-local/zshrc
touch ~/.dotfiles-local/zshrc-post
touch ~/.dotfiles-local/vimrc
touch ~/.dotfiles-local/vimrc-post
touch ~/.dotfiles-local/vimrc-plug
touch ~/.dotfiles-local/tmux.conf

if [ -f ~/.dotfiles-local/setup ]; then
    print "Running ~/.dotfiles-local/setup"
    ~/.dotfiles-local/setup
fi

export GIT_DIR=$DIR/.git
git config --global color.ui true
git config user.name "Grumpy"
git config user.email "grumpy@123koz.com"
git remote set-url origin https://grumpy123@github.com/grumpy123/dotfiles.git
git config --global credential.helper 'cache --timeout=28800' #8h

git config --global diff.tool vimdiff
git config --global difftool.prompt false

git config --global alias.st status
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.br branch

